name: example
description: "An example for nesigner sdk."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ndk: ^0.3.2
  flutter_nesigner_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  pointycastle: ^4.0.0
  # ffi: ^2.1.4

flutter:
  uses-material-design: true
