name: flutter_nesigner_sdk
description: "A flutter client sdk for nesigner."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_libserialport: ^0.5.0
  crypto: ^3.0.6
  kepler: ^1.0.3
  pointycastle: ^3.6.0
  hex: ^0.2.0
  cryptography: ^2.7.0
  # cryptography_flutter: ^2.3.2
  cryptography_flutter:
    git:
        url: https://github.com/mvarendorff/cryptography
        ref: fix/compatibility-agp-8x
        path: cryptography_flutter
  bip340: ^0.3.0
  string_validator: ^1.1.0
  usb_serial: ^0.5.2
  # libusb: 0.4.23-dev.1+1
  # libusb:
  #   path: ../libusb_ffi/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  # ffi: ^2.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_nesigner_sdk
        pluginClass: FlutterNesignerSdkPlugin
      ios:
        pluginClass: FlutterNesignerSdkPlugin
      linux:
        pluginClass: FlutterNesignerSdkPlugin
      macos:
        pluginClass: FlutterNesignerSdkPlugin
      windows:
        pluginClass: FlutterNesignerSdkPluginCApi
